name: CI/CD for Dev Environment
 
on:
  push:
    branches:
      - main  # Run the workflow on every commit to the 'dev' branch
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures we can compare changes properly
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
 
      - name: Create PEM file from Secret
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
 
      - name: Ensure the target directory exists on EC2
        run: |
            ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p ~/backend-dev && sudo chmod -R 777 ~/backend-dev"
 
      - name: Install Node.js, npm, PM2 and Nginx if not installed
        run: |
          ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            # Install Node.js and npm if missing
            if ! command -v npm >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
 
            # Install PM2 if missing
            if ! command -v pm2 >/dev/null 2>&1; then
              sudo npm install -g pm2
            fi
 
            # Install Nginx if missing
            if ! command -v nginx >/dev/null 2>&1; then
              sudo apt-get update -y
              sudo apt-get install -y nginx
              sudo systemctl enable nginx
              sudo systemctl start nginx
            fi
 
            node -v
            npm -v
            pm2 -v
          '
 
      - name: Copy files to EC2
        run: |
          # Copy all files to the remote EC2 directory
          scp -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no -r * ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/backend-dev/
 
      - name: Install dependencies
        run: |
          # Install dependencies if package.json was changed
          ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd ~/backend-dev && npm install --force"
 
      - name: Restart server service on EC2
        run: |
          # Restart PM2 to apply changes
          ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'pm2 restart server-dev'
 